-- 临时关闭行级安全策略，让注册功能正常工作
-- 注意：这是为了开发测试，正式环境需要开启安全策略

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE files DISABLE ROW LEVEL SECURITY;
ALTER TABLE learning_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE file_chunks DISABLE ROW LEVEL SECURITY;